Add secondary menu items as an alternative to using multiple icons
Korkman/macemu-appimage-builder pull request #16
Opened 2022-09-09 22:59 UTC by robxnano

.desktop files have the ability to define multiple shortcuts with their own names and commands. If you add these to the existing shortcuts, there wouldn't be a need to have separate icons for GUI and non-GUI modes. Example of how they appear: 
![Screenshot from 2022-09-07 23-36-27](https://user-images.githubusercontent.com/89391914/189456474-6e4829ca-2487-48ad-8766-d360d2182acf.png)

Secondary menu items are supported on most major desktop environments, and are typically accessed by right-clicking on the launcher or taskbar icons.
I added an extra command-line argument to the AppRun wrapper to create a single shortcut. Due to the added complexity of the .desktop files, I had to use sed to insert the titles and paths, and I haven't had time to set up a Docker instance to test the build process yet. But please take a look and see how it could be useful.

2022-09-24 21:50 UTC, Korkman commented on docker/build/apprun-hook-install.sh
> +	APPIMAGE="/home/rob/Apps/SheepShaver/SheepShaver-x86_64.AppImage"
This needs cleaning

2022-09-24 21:51 UTC, Korkman requested changes
Great idea! I like it. This also eases integration with AppImageLauncher (having two desktop files breaks compatibility).

2022-09-25 12:10 UTC, Korkman approved these changes
Will test locally and clean-up now

2022-09-25 12:11 UTC, merged

2022-09-25 17:22 UTC, Korkman commented
I modified your changes a bit. The result is now merged in main and available on the [release page](https://github.com/Korkman/macemu-appimage-builder/releases). Thank you for contributing!

2022-09-26 12:20 UTC, robxnano commented
Thanks for fixing it up for me - it works great!